format = """
$batteryğŸŒ‘ ğŸŒ’ ğŸŒ“ ğŸŒ” ğŸŒ• ğŸŒ– ğŸŒ— ğŸŒ˜ ğŸŒ‘ $os$env_var$memory_usage 
ğ–¥§ğ“‹¼ğ–¤£ğ–¥§ğ“‹¼ğ“Šğ“‹¼ğ“Šğ“‹¼ğ–¥§ğ–¤£ğ“‹¼ğ–¤£ğ–¥§ğ“‡—ğ–¥§ğ“‹¼ğ–¤£ğ–¥§ğ“‹¼ğ“Šğ“‹¼ğ“Šğ“‹¼ğ–¥§ğ–¤£$username $hostname $localip
$status[ğ’…’ğ’ˆ”ğ’…’ğ’‡«ğ’„†ğŸ‘¾](bg:#000000 fg:#240046)\
$shlvl\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$bun\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$sudo\
$cmd_duration\
$jobs\
$container\
â–’[â–’â•‘â–ˆâ–’](fg:#ff8500 bg:#240046)\
[â•‘](bg:#ff8500 fg:#240046)\
$directory\
[î‚´](fg:#ff9100 bg:#ff9e00)\
[î‚´](fg:#ff9e00 bg:#240046)\
$time\
[î‚´ ](fg:#240046)\
[ğŸŒ›](bg:#000000)\n\
$shell$character"""

[cmd_duration]
min_time = 500
format = '[elapsedâ±ï¸$duration](bg:#240046 fg:#ff9e00)'

[fill]
symbol = '.'
style = 'bold black'

[directory]
style = "fg:#ff9100 bg:#240046"
format = "[â–’â•‘â–ˆâ–“â–’](bg:#000000 fg:#240046)[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦ğ“‚€..."

[character]
success_symbol = 'ğ“›[îƒ„îƒ†ó°¢šîƒ‡îƒ…](bold green) '
error_symbol = 'ğ“‡˜[ó°®¢](bold red)[ó°šŒ](white)[ó°®¢](bold red) '
vimcmd_symbol = 'ğ“†‘[î˜«âœ](bold green) '
vimcmd_replace_one_symbol = 'ğ“†·[âœâœâœî˜« î¬½](bold purple) '
vimcmd_replace_symbol = 'ğ“„¹[î˜«âœ î¬¼](bold purple) '
vimcmd_visual_symbol = 'ğ“„®[î˜« ó°›”âœâœ](bold yellow) '
disabled = false
format = '[$symbol]($style)'


[directory.substitutions]
"Documents" = "ğ“† ğŸ“„ Documents"
"Downloads" = "ğ“†° ğŸ“‚ Downloads"
"Music" = "ğ“‡¬ ğŸµ Music"
"Pictures" = "ğ“†‘ ğŸ–¼ï¸ Pictures"
"Videos" = "ğ“‡› ğŸ“¹ Videos"
"Steam" = "ğ“† ğŸ® Steam"
"A1111" = "ğ“´ğ“›ğ“†‘ ğŸ¤– A1111"
"ComfyUI" = "ğ“‡‹ğ“†‘ğ“‡‹ ğŸ›‹ï¸ ComfyUI"
"Program Files" = "ğ“ ğ“†ğ“†¤ğ“‡‰ ğŸ“‚ Program Files"
"Program Files (x86)" = "ğ“ ğ“†ğ“†¤ğ“‡‰86 ğŸ“‚ Program Files (x86)"
"Desktop" = "ğ“†‘ğ“† ğŸ’» Desktop"
"Projects" = "ğ“ ğ“†ğ“†¤ğ“‡‰ ğŸ“‚ Projects"
"Photos" = "ğ“‡·ğ“† ğŸ“· Photos"
"Games" = "ğ“†ğ“´ğ“†¤ ğŸ® Games"
"Work" = "ğ“†°ğ“‡Œ ğŸ’¼ Work"
"School" = "ğ“†¢ğ“€¢ ğŸ“š School"
"Temp" = "ğ“†ğ“‡— ğŸŒ¡ï¸ Temp"
"Public" = "ğ“†ğ“‡ğ“†¤ ğŸŒ Public"
"Private" = "ğ“‡“ğ“‡ğ“‡˜ ğŸ”’ Private"
"Backup" = "ğ“†ğ“‡ğ“‡ğ“‡˜ ğŸ’¾ Backup"
"Books" = "ğ“†¢ğ“‡œ ğŸ“š Books"
"Scripts" = "ğ“‡œğ“† ğ“„€ğ“‡´ ğŸ“œ Scripts"
"Archives" = "ğ“‡Œğ“†¤ğ“„€ğ“‡´ ğŸ—„ï¸ Archives"
"Images" = "ğ“‡¶ğ“‡·ğ“‡˜ ğŸ–¼ï¸ Images"
"Audio" = "ğ“†©ğ“†¤ğ“†¡ ğŸ”Š Audio"
"Fonts" = "ğ“† ğ“‡œğ“†© ğŸ”  Fonts"
"Recycle Bin" = "ğ“‡¤ğ“—ğ“‡ğ“‡˜ ğŸ—‘ï¸ Recycle Bin"
"Finance" = "ğ“†’ğ“†¤ ğŸ’° Finance"
"System" = "ğ“†¤ğ“„¯ğ“„¢ âš™ï¸ System"
"Config" = "ğ“†¤ğ“„¯ğ“„¢ âš™ï¸ Config"
"Logs" = "ğ“‡œğ“†¤ğ“„€ğ“‡´ ğŸ“œ Logs"
"Mail" = "ğ“€«ğ“†¡ğ“„€ğ“‡´ âœ‰ï¸ Mail"
"Templates" = "ğ“‡’ğ“†¤ğ“„€ğ“‡´ ğŸ“„ Templates"
"VirtualBox VMs" = "ğ“‡»ğ“‡ˆğ“„€ğ“„¯ğ“„š ğŸ’» VirtualBox VMs"
"Web" = "ğ“‡ğ“‡ˆğ“„€ ğŸŒ Web"
"Archive" = "ğ“‡Œğ“„€ğ“‡´ ğŸ—„ï¸ Archive"
"Old" = "ğ“‡‹ğ“„€ğ“‡´ ğŸ•°ï¸ Old"
"New" = "ğ“‡ğ“„€ ğŸ†• New"
"PDFs" = "ğ“‡’ğ“„®ğ“‡˜ ğŸ“„ PDFs"
"Ebooks" = "ğ“†¢ğ“†‘ğ“‡œ ğŸ“š Ebooks"
"Adobe" = "ğ“„¨ğ“‡ğ“† ğ“„€ğ“„¨ ğŸ¨ Adobe"
"IDE" = "ğ“‡»ğ“†¡ğ“†¡ ğŸ’» IDE"
"Code" = "ğ“‡»ğ“†¡ğ“†¡ ğŸ’» Code"
"Programming" = "ğ“‡»ğ“†¡ğ“†¡ğ“„€ğ“„¯ğ“„š ğŸ’» Programming"
"Development" = "ğ“‡»ğ“†¡ğ“†¡ğ“„€ğ“„¯ğ“„š ğŸ’» Development"
"Emulators" = "ğ“‡´ğ“…¨ğ“†¡ğ“„€ğ“„¯ğ“„š EMUğŸ® Emulators"
"NES" = "ğ“‰¼ ğŸ•¹ï¸NES"
"SNES" = "ğ“Šƒğ“‰¼ SNESğŸ•¹ï¸"
"N64" = "ğ“Ÿğ“‰¼ 64ğŸ•¹ï¸"
"PlayStation" = "ğ“‡»ğ“‡ğ“‡ğ“‡˜ PSğŸ®ğ“Ÿ"
"Xbox" = "ğ“‡»ğ“‡ğ“‡ğ“‡˜XB ğŸ®ğ“Ÿ"
"GameBoy" = "ğ“‰¼ GBğŸ•¹ï¸"
"DS" = "ğ“Šƒğ“‰¼ ğŸ•¹ï¸DS"
"3DS" = "ğ“Ÿğ“‰¼ ğŸ•¹ï¸3DS"
"PSP" = "ğ“ğ“ğ“ğ“‡˜ğ“ ğŸ®ğ“ŸPSPğŸ‘¾"
"PS2" = "ğ“ğ“ğ“ğ“‡˜ğ“ ğŸ®ğ“ŸPS2ï¸âƒ£"
"PS3" = "ğ“ğ“ğ“ğ“‡˜ğ“ ğŸ®ğ“ŸPS3ï¸âƒ£"
"PS4" = "ğ“ğ“ğ“ğ“‡˜ğ“ ğŸ®ğ“ŸPS4ï¸âƒ£"
"Xbox 360" = "ğ“ğ“ğ“ğ“‡˜ğ“ ğŸ®ğ“Ÿ360"
"Xbox One" = "ğ“ğ“ğ“ğ“‡˜ğ“ ğŸ®ğ“ŸOne"
"Switch" = "ğ“‡·ğ“‡ğ“‡ğ“‡˜ SWITCHğŸ®ğ“Ÿ"
"PC" = "ğ“€‚ğ“†¢ğ“†¤ ï…º"
"Mac" = "ğ“‹´ ï…¹"
"Linux" = "ğ“‡´ğ“‰” ï…¼ "
"A:" = "ğ“‡Œ (Ankh)"
"B:" = "ğ“†£ (Bennu)"
"C:" = "ğ“†“ (Cleopatra)"
"D:" = "ğ“…” (Djoser)"
"E:" = "ğ“‡ (Eset)"
"F:" = "ğ“‡‹ (Fayum)"
"G:" = "ğ“‡Š (Geb)"
"H:" = "ğ“‡ (Horus)"
"I:" = "ğ“² (Isis)"
"J:" = "ğ“› (Jed)"
"K:" = "ğ“† (Khepri)"
"L:" = "ğ“†‰ (Lapis Lazuli)"
"M:" = "ğ“‡— (Ma'at)"
"N:" = "ğ“  (Nefertiti)"
"O:" = "ğ“†“ (Osiris)"
"P:" = "ğ“‡¯ (Ptah)"
"Q:" = "ğ“‡° (Queen)"
"R:" = "ğ“— (Ra)"
"S:" = "ğ“‡¤ (Seshat)"
"T:" = "ğ“´ (Tutankhamun)"
"U:" = "ğ“†˜ (Udjat)"
"V:" = "ğ“‡› (Vizier)"
"W:" = "ğ“  (Wadjet)"
"X:" = "ğ“¢ (Xerxes)"
"Y:" = "ğ“† (Yuya)"
"Z:" = "ğ“ (Zoser)"
"Android" = "âš™ï¸ (ğ“†¤ğ“„¯ğ“„¢ Android)"
"Apple iPhone" = "ğŸ (ğ“‹´ Apple iPhone)"
"DVD-ROM" = "ğŸ’¿ (ğ“‡œğ“—ğ“ğ“ğ“‡˜ DVD-ROM)"
"DVD-RW" = "ğŸ“€ (ğ“‡œğ“ğ“†¤ğ“‡˜ DVD-RW)"
"CD-ROM" = "ğŸ’¿ (ğ“‡œğ“—ğ“ğ“ğ“‡˜ CD-ROM)"
"BD-RE" = "ğŸ“€ (ğ“‡œğ“†‹ğ“—ğ“‡˜ BD-RE)"
"Windows" = "ğŸªŸ (ğ“¤ğ“ğ“‡´ğ“¤ğ“ğ“ Windows)"

[singularity]
symbol = "ğŸŒ€ "
style = "bg:#17000b"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#17000b)]($style)'

[kubernetes]
symbol = 'ğŸš¢ '
format = '[$symbol$context( \($namespace\))]($style) in '
style = 'cyan bold'
disabled = false
[kubernetes.context_aliases]
'dev.local.cluster.k8s' = 'dev'
'.*/openshift-cluster/.*' = 'openshift'
'gke_.*_(?P<var_cluster>[\w-]+)' = 'gke-$var_cluster'
[kubernetes.user_aliases]
'dev.local.cluster.k8s' = 'dev'
'root/.*' = 'root'

[vcsh]
symbol = "ğŸ’½"
style = "bg:#007ec6"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#007ec6)]($style)'

[fossil_branch]
symbol = 'ğŸ¦ '
style = 'bold purple'
truncation_length = 4
truncation_symbol = ''
disabled = false

[gcloud]
format = 'on [$symbol$account(@$domain)(\($region\))]($style) '
symbol = 'ï† â˜ï¸ '
region_aliases = { us-central1 = 'uc1', asia-northeast1 = 'an1' }
project_aliases = { very-long-project-name = 'vlpn' }
style = 'bold blue'
disabled = false

[git_branch]
format = " $symbol$branch "
symbol = "ğŸ£ "
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '($state( $progress_current of $progress_total)) '

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count}"
behind = "ğŸ¢ Ã—${count}"
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
untracked = "ğŸ›¤ï¸ Ã—${count}"
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count}"
staged = "ğŸ—ƒï¸ Ã—${count}"
renamed = "ğŸ“› Ã—${count}"
deleted = "ğŸ—‘ï¸ Ã—${count}"
style = "bright-white"
format = "$all_status$ahead_behind"

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[hg_branch]
format = 'on [ â˜¿ $branch](bold purple)'
truncation_length = 4
truncation_symbol = 'x'

[pijul_channel]
symbol = "ğŸ¦€"
style = "bg:#240046"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#240046)]($style)'

[docker_context]
format = 'via [$symbol$context]($style) '
symbol = 'ğŸ³ '
only_with_files = true
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
style = 'blue bold'
disabled = false

[package]
format = 'via [ğŸ“¦ $version](208 bold) '

[c]
format = 'ğ“™ [$symbol($version(-$name) )]($style)'
version_format = 'v${raw}'
symbol = 'î˜ğŸ…’ '
detect_extensions = ['c', 'h']
detect_files = []
detect_folders = []
commands = [['cc', '--version'], ['gcc', '--version'], ['clang', '--version']]
style = 'bold 149'
disabled = false

[cmake]
format = 'via [$symbol($version )]($style)'
version_format = 'v${raw}'
symbol = 'ó°™±î™³'
detect_extensions = []
detect_files = ['CMakeLists.txt', 'CMakeCache.txt']
detect_folders = []
style = 'bold blue'
disabled = false

[bun]
format = 'via [$symbol($version )]($style)'
version_format = 'v${raw}'
symbol = 'ğŸ” '
detect_extensions = []
detect_files = ['bun.lockb', 'bunfig.toml']
detect_folders = []
style = 'bold red'
disabled = false

[cobol]
symbol = 'â˜ ï¸ '
format = 'via [$symbol($version )]($style)'
version_format = 'v${raw}'
style = 'bold blue'
detect_extensions = ['cbl', 'cob', 'CBL', 'COB']
detect_files = []
detect_folders = []
disabled = false

[daml]
format = 'via [$symbol($version )]($style)'
version_format = 'v${raw}'
symbol = 'î™‘ '
style = 'bold cyan'
detect_extensions = []
detect_files = ['daml.yaml']
detect_folders = []
disabled = false

[dart]
format = 'via [$symbol($version )]($style)'
version_format = 'v${raw}'
symbol = 'ğŸ¯ '
detect_extensions = ['dart']
detect_files = ['pubspec.yaml', 'pubspec.yml', 'pubspec.lock']
detect_folders = ['.dart_tool']
style = 'bold blue'
disabled = false

[deno]
format = 'via [$symbol($version )]($style)'
version_format = 'v${raw}'
symbol = 'ğŸ¦• '
detect_files = ['deno.json', 'deno.jsonc', 'mod.ts', 'mod.js', 'deps.ts', 'deps.js']
style = 'green bold'
disabled = false

[dotnet]
format = 'via [$symbol($version )(ğŸ¯ $tfm )]($style)'
version_format = 'v${raw}'
symbol = '.NET '
heuristic = true
detect_extensions = ['csproj', 'fsproj', 'xproj']
detect_files = ['global.json', 'project.json', 'Directory.Build.props', 'Directory.Build.targets', 'Packages.props']
style = 'bold blue'
disabled = false

[elixir]
format = 'via [$symbol($version \(OTP $otp_version\) )]($style)'
version_format = 'v${raw}'
symbol = 'ïƒî˜­ '
detect_files = ['mix.exs']
style = 'bold purple'
disabled = false

[elm]
format = 'via [$symbol($version )]($style)'
version_format = 'v${raw}'
symbol = 'ğŸŒ³î˜¬ '
detect_extensions = ['elm']
detect_files = ['elm.json', 'elm-package.json', '.elm-version']
detect_folders = ['elm-stuff']
style = 'cyan bold'
disabled = false

[erlang]
format = 'via [ó°«² $version](bold red) '

[fennel]
symbol = "îš¯"
style = "bg:#548687"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#548687)]($style)'

[golang]
format = 'via [ $symbol ($version) ]($style)'
symbol = 'ğŸ¹ '
detect_extensions = ['go']
detect_files = ['go.mod', 'go.sum', 'go.work', 'glide.yaml', 'Gopkg.yml', 'Gopkg.lock', '.go-version']
detect_folders = ['Godeps']
style = 'bold cyan'
not_capable_style = 'bold red'
disabled = false

[guix_shell]
disabled = true
format = 'via [â™ˆ](#474747) '

[haskell]
format = 'via [Î» $version]($style)'
symbol = 'Î» '
detect_extensions = ['hs', 'cabal', 'hs-boot']
detect_files = ['stack.yaml', 'cabal.project']
style = 'bold purple'
disabled = false

[haxe]
format = 'via [âŒ˜ $version](bold fg:202) '
detect_extensions = ['hx', 'hxml']
detect_files = ['project.xml', 'Project.xml', 'application.xml', 'haxelib.json', 'hxformat.json', '.haxerc']
detect_folders = ['.haxelib', 'haxe_libraries']
symbol = 'âŒ˜ '
style = 'bold fg:202'
disabled = false

[helm]
format = 'via [âˆ $version](bold white) '
detect_extensions = []
detect_files = ['helmfile.yaml', 'Chart.yaml']
detect_folders = []
symbol = 'âˆğŸ› '
style = 'bold white'
disabled = false

[java]
format = 'via [${symbol}(${version} )]($style)'
version_format = 'v${raw}'
detect_extensions = ['java', 'class', 'gradle', 'jar', 'cljs', 'cljc']
detect_files = ['pom.xml', 'build.gradle.kts', 'build.sbt', '.java-version', 'deps.edn', 'project.clj', 'build.boot', '.sdkmanrc']
detect_folders = []
symbol = 'â˜• '
style = 'red dimmed'
disabled = false

[julia]
symbol = 'à®ƒ '
style = 'bold purple'
disabled = false

[kotlin]
symbol = 'ğŸ…º '
style = 'bold blue'
disabled = false

[gradle]
format = 'via [ğŸ…¶ $version]($style)'
symbol = 'ğŸ…¶ '
detect_extensions = ['gradle', 'gradle.kts']
detect_folders = ['gradle']
style = 'bold bright-cyan'
disabled = false
recursive = false

[lua]
format = 'via [ğŸŒœ $version](bold blue) '

[nim]
format = 'via [$symbol($version )]($style)'
version_format = 'v${raw}'
symbol = 'ğŸ‘‘ '
detect_extensions = ['nim', 'nims', 'nimble']
detect_files = ['nim.cfg']
detect_folders = []
style = 'bold yellow'
disabled = false

[nodejs]
symbol = "â¬¢"
style = "bg:#8cc84b"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#8cc84b)]($style)'

[ocaml]
format = 'via [$symbol($version)(\($switch_indicator$switch_name\) )]($style)'
version_format = 'v${raw}'
symbol = 'ğŸ« '
global_switch_indicator = ''
local_switch_indicator = '*'
detect_extensions = ['opam', 'ml', 'mli', 're', 'rei']
detect_files = ['dune', 'dune-project', 'jbuild', 'jbuild-ignore', '.merlin']
detect_folders = ['_opam', 'esy.lock']
style = 'bold yellow'
disabled = false

[opa]
format = 'via [$symbol($version )]($style)'
version_format = 'v${raw}'
symbol = 'ğŸª– '
detect_extensions = ['rego']
style = 'bold blue'
disabled = false

[perl]
symbol = "ğŸª"
style = "bg:#0298c3"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#0298c3)]($style)'

[php]
symbol = "ğŸ˜"
style = "bg:#4f5d95"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#4f5d95)]($style)'

[pulumi]
symbol = "ğŸ’¨"
style = "bg:#512bd4"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#512bd4)]($style)'

[purescript]
symbol = "ğŸƒ"
style = "bg:#1d222d"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#1d222d)]($style)'

[python]
symbol = "ğŸ"
style = "bg:#3776ab"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#3776ab)]($style)'

[raku]
symbol = "ğŸ¦‹"
style = "bg:#000000"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#000000)]($style)'

[rlang]
symbol = "ğŸ“Š"
style = "bg:#276dc3"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#276dc3)]($style)'

[red]
symbol = "ğŸ”´"
style = "bg:#000000"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#000000)]($style)'

[ruby]
symbol = "ğŸ’"
style = "bg:#cc342d"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#cc342d)]($style)'

[rust]
symbol = "ğŸ¦€"
style = "bg:#240046"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#240046)]($style)'

[scala]
symbol = "â‰¡"
style = "bg:#dc322f"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#dc322f)]($style)'

[solidity]
symbol = "ğŸš§"
style = "bg:#363636"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#363636)]($style)'

[swift]
symbol = "ğŸ¦"
style = "bg:#ffac45"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#ffac45)]($style)'

[terraform]
symbol = "ğŸŒ"
style = "bg:#5e5086"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#5e5086)]($style)'

[vlang]
symbol = "âœ“"
style = "bg:#3d87a8"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#3d87a8)]($style)'

[zig]
symbol = "ó°¬‡"
style = "bg:#ec915c"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#ec915c)]($style)'

[buf]
format = 'with [ğ“„‹($version )]($style)'
version_format = 'v${raw}'
symbol = 'ğŸƒğŸ“¦ '
detect_extensions = []
detect_files = ['buf.yaml', 'buf.gen.yaml', 'buf.work.yaml']
detect_folders = []
style = 'bold blue'
disabled = false

[nix_shell]
format = 'via [$symbol$state( \($name\))]($style) '
symbol = 'â„ï¸ '
style = 'bold blue'
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'
disabled = false
heuristic = false

[conda]
truncation_length = 3
symbol = 'ğŸ '
style = 'bold green'
format = 'via [$symbol$environment]($style) '
ignore_base = true
disabled = false

[meson]
disabled = false
truncation_symbol = '--'
symbol = ' '
style = 'bold dimmed green'
[spack]
symbol = "ğŸ“¦ğŸ—ï¸"
style = "bg:#4e7fff"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#4e7fff)]($style)'

[memory_usage]
disabled = false
threshold = -1
symbol = 'ğŸ§  '
style = 'bold dimmed green'

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'
symbol = 'ğŸ…° '

[aws.region_aliases]
ap-southeast-2 = 'au'
us-east-1 = 'va'
[aws.profile_aliases]
CompanyGroupFrobozzOnCallAccess = 'Frobozz'

[openstack]
format = 'on [$symbol$cloud(\($project\))]($style) '
symbol = 'Oâ˜ï¸ '
style = 'bold yellow'
disabled = false

[azure]
disabled = false
format = 'on [$symbol($username)($subscription)]($style) '
symbol = 'î¯˜â˜ï¸'
style = 'blue bold'

[env_var]
variable = 'USERPROFILE'
default = 'unknown user'
symbol = 'â€¦ğ“‚€...'
format = ' with[$username $env_value]($style) '
style = 'black bold dimmed'
disabled = false

[crystal]
symbol = 'ğŸ”®âœ¨'
format = 'via [$symbol($version )]($style)'
version_format = 'v${raw}'
style = 'bold  purple'
detect_extensions = ['cr']
detect_files = ['shard.yml']
detect_folders = []
disabled = false

[jobs]
symbol = 'ğŸ‘·âœ¦ '
number_threshold = 3
symbol_threshold = 1
format = '[$symbol$number]($style) '
style = 'bold blue'
disabled = false

[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '
unknown_symbol = 'â“ '
empty_symbol = 'ğŸ”Œ '
format = '[$symbol$percentage]($style) '
disabled = false

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 30
style = 'bold yellow'
discharging_symbol = 'ğŸ©¸'

[status]
style = 'bg:blue'
symbol = 'âš ï¸'
success_symbol = 'âœ…'
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[os]
format = "on [$symbol($name )]($style)"
style = "bold blue"
disabled = false

[os.symbols]
Alpaquita = "ğŸ”” "
Alpine = "ğŸ”ï¸ "
Amazon = "ğŸ™‚ "
Android = "ğŸ¤– "
Arch = "ğŸ—ï¸ "
Artix = "ğŸ—ï¸ "
CentOS = "ğŸ’  "
Debian = "ğŸŒ€ "
DragonFly = "ğŸ‰ "
Emscripten = "ğŸ”— "
EndeavourOS = "ğŸš€ "
Fedora = "ğŸ© "
FreeBSD = "ğŸ˜ˆ "
Garuda = "ğŸ¦… "
Gentoo = "ğŸ—œï¸ "
HardenedBSD = "ğŸ›¡ï¸ "
Illumos = "ğŸ¦ "
Linux = "ğŸ§ "
Mabox = "ğŸ“¦ "
Macos = "ğŸ "
Manjaro = "ğŸ¥­ "
Mariner = "ğŸŒŠ "
MidnightBSD = "ğŸŒ˜ "
Mint = "ğŸŒ¿ "
NetBSD = "ğŸš© "
NixOS = "â„ï¸ "
OpenBSD = "ğŸ¡ "
OpenCloudOS = "â˜ï¸ "
openEuler = "ğŸ¦‰ "
openSUSE = "ğŸ¦ "
OracleLinux = "ğŸ¦´ "
Pop = "ğŸ­ "
Raspbian = "ğŸ“ "
Redhat = "ğŸ© "
RedHatEnterprise = "ğŸ© "
Redox = "ğŸ§ª "
Solus = "â›µ "
SUSE = "ğŸ¦ "
Ubuntu = "ğŸ¯ "
Unknown = "â“ "
Windows = "ğŸªŸ "

[container]
symbol = "ğŸ«™"
style = "bg:#007ec6"
format = '[[ $symbol ($version) ](fg:#ff9e00 bg:#007ec6)]($style)'

[shell]
bash_indicator = 'bsh'
fish_indicator = 'fsh'
zsh_indicator = 'zsh'
powershell_indicator = 'psh'
ion_indicator = 'ion'
elvish_indicator = 'esh'
tcsh_indicator = 'tsh'
xonsh_indicator = 'xsh'
cmd_indicator = 'cmd'
nu_indicator = 'nu'
unknown_indicator = 'mystery shell'
format = '[$indicator]($style) '
style = 'cyan bold'
disabled = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#240046"
format = '[[ ğŸˆ $time ](fg:#ff9e00 bg:#240046)]($style)'
ssh_only = false
ssh_symbol = 'ğŸŒğ“‚€ '


[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)  ğ“‚€  [$hostname](bold red) '
trim_at = '.companyname.com'
disabled = false
style = 'bold dimmed green'

[localip]
ssh_only = false
format = 'ğ“‚€ [$localipv4](bold red) '
disabled = false
